/*
** 用于练习使用的数据
** 为原始数据，有错误
*/

-- 创建数据库
CREATE DATABASE practice;

-- 使用数据库
USE practice;

-- 插入数据
INSERT INTO department(d_name) VALUES('信息管理学院');
INSERT INTO department(d_name) VALUES('经济管理学院');
INSERT INTO department(d_name) VALUES('理学院');
INSERT INTO department(d_name) VALUES('机械与电力学院');
INSERT INTO department(d_name) VALUES('计算机学院');
INSERT INTO department(d_name) VALUES('外国语学院');
INSERT INTO department(d_name) VALUES('建筑学院');
INSERT INTO department(d_name) VALUES('公共管理学院');
INSERT INTO department(d_name) VALUES('政治教育学院');
INSERT INTO department(d_name) VALUES('医学院');
INSERT INTO department(d_name) VALUES('人文学院');


INSERT INTO course(c_name, c_hours, c_credit) VALUES('建筑的文化理解', 16, 1);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('建筑发展趋向', 24, 1);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('建筑节能导论', 32, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('建筑技术概论', 16, 1);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('中国古代建筑史纲', 32, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('空间形体表达基础', 32, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('建筑声环境', 16, 1);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('城市规划原理', 32, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('建筑数学', 32, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('生态建筑设计策略导论', 16, 1);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('建筑构造', 48, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('人居科学基础', 16, 1);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('古建测绘实习', 16, 1);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('乡土建筑学', 16, 1);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('公共雕塑艺术', 32, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('建筑细部设计', 32, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('风景园林学导论', 16, 1);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('科研思维方法', 32, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('机器人工程基础及应用', 32, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('科技商务', 32, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('产品设计与开发', 32, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('生物材料工程与器件', 32, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('绿色制造与可持续发展', 16, 1);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('表面工程基础', 32, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('工程生物学基础', 32, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('有限元分析', 32, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('机电控制系统实践', 32, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('工程材料', 48, 3);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('工程制图基础', 48, 3);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('机械设计基础', 48, 3);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('机械工程导论', 48, 3);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('控制工程基础', 48, 3);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('制造工程基础', 48, 3);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('微纳米工程材料', 32, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('制造工程信息技术', 48, 3);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('设计与制造基础实践', 160, 4);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('制造工程基础', 54, 3);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('设计与制造', 80, 4);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('微纳米工程材料', 48, 3);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('特种加工工艺', 32, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('信号处理', 64, 3);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('材料加工工艺', 48, 3);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('制造系统', 32, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('工业产品造型设计', 32, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('机器人技术与应用', 32, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('生产系统规划与设计', 32, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('微纳制造导论', 32, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('机械材料学', 48, 3);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('计算机辅助设计技术基础', 48, 3);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('软件工程', 96, 3);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('人工智能导论', 32, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('面向计算机科学的离散数学', 48, 3);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('数据结构', 64, 4);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('计算机组成与系统结构', 64, 4);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('计算机网络', 48, 3);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('下一代互联网', 32, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('计算基因组分析', 48, 3);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('C++语言程序设计', 64, 3);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('操作系统', 48, 3);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('语言程序设计', 48, 3);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('办公自动化软件应用', 40, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('并行计算基础', 56, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('网页设计与制作', 48, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('嵌入式系统设计与应用', 32, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('数据挖掘：方法与应用', 48, 3);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('初等数论', 32, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('计算机文化基础', 32, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('数据库技术及应用', 48, 3);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('计算机程序设计基础', 48, 3);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('人工智能导论', 32, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('信号处理原理', 48, 3);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('编译原理', 64, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('数字逻辑实验', 32, 1);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('系统分析与控制', 48, 3);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('系统分析与控制', 32, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('信息检索', 32, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('模式识别', 32, 2);
INSERT INTO course(c_name, c_hours, c_credit) VALUES('现代控制技术', 36, 2);


INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('王蔚', '女', 22, 3);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('李泽源', '男', 22, 8);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('林艳', '女', 22, 1);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('殷畅', '女', 22, 5);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('权洪林', '女', 22, 1);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('董佳', '女', 22, 2);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('陈棋颖', '女', 22, 6);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('马尚芳', '女', 22, 1);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('葛子欣', '女', 22, 4);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('李万青', '女', 22, 7);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('岳媛', '女', 22, 3);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('汤小朋', '女', 22, 9);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('杨菁筠', '女', 22, 1);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('张可佳', '女', 22, 10);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('蔡倩瑜', '女', 23, 6);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('张伟', '男', 22, 11);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('王春鸣', '女', 22, 1);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('鲁丹', '女', 22, 8);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('常竞', '女', 22, 5);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('陈良华', '男', 22, 6);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('孟子钰', '女', 22, 4);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('芮安妮', '女', 22, 7);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('杨雪莉', '女', 22, 2);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('诸萌', '女', 22, 1);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('罗政', '男', 21, 9);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('陈燕', '女', 22, 6);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('吴瑶', '女', 22, 3);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('王维', '女', 22, 2);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('麻瑞瑶', '女', 22, 1);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('谭卉宁', '女', 23, 1);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('周梦鑫', '女', 22, 1);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('吴禹非', '男', 21, 1);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('岳永杰', '男', 22, 3);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('郑婉滢', '女', 22, 1);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('王环', '女', 23, 9);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('程昊', '男', 22, 10);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('朴一君', '男', 22, 2);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('董晨', '男', 22, 4);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('陈玉立', '男', 22, 7);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('韩莹', '女', 22, 4);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('张亚丽', '女', 22, 6);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('郑瀚潇', '男', 22, 3);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('王婧璇', '女', 22, 1);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('孙雨晨', '男', 22, 1);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('唐凯城', '男', 21, 11);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('石晗', '女', 22, 6);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('田甜', '女', 22, 8);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('赵旭彤', '女', 22, 9);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('刘联博', '男', 21, 1);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('胡亚楠', '女', 22, 4);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('钟泽昊', '男', 22, 6);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('张露雨', '女', 22, 7);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('张增慧', '女', 22, 4);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('江帆', '女', 23, 5);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('李晨希', '男', 22, 1);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('杨菁', '女', 22, 1);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('李晨曦', '女', 22, 3);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('张勇', '男', 23, 1);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('李萍', '女', 22, 1);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('张文', '女', 22, 1);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('贾冬雪', '女', 22, 8);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('王振', '男', 22, 10);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('董宁', '男', 22, 5);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('赵阳', '男', 22, 7);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('都宇成', '男', 22, 12);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('任大为', '男', 22, 6);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('徐文清', '女', 23, 9);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('李涵', '女', 22, 10);
INSERT INTO student(s_name, s_sex, s_age, s_department) VALUES('孟繁琪', '男', 22, 1);

-- s70 c 79
INSERT INTO curricula_variable VALUES(5, 6, 80);
INSERT INTO curricula_variable VALUES(3, 6, 84);
INSERT INTO curricula_variable VALUES(7, 6, 65);
INSERT INTO curricula_variable VALUES(10, 6, 75);
INSERT INTO curricula_variable VALUES(32, 6, 90);
INSERT INTO curricula_variable VALUES(9, 6, 56);
INSERT INTO curricula_variable VALUES(45, 6, NULL);
INSERT INTO curricula_variable VALUES(5, 4, 66);
INSERT INTO curricula_variable VALUES(6, 4, 70);
INSERT INTO curricula_variable VALUES(8, 4, 95);
INSERT INTO curricula_variable VALUES(52, 10, 88);
INSERT INTO curricula_variable VALUES(15, 10, 74);
INSERT INTO curricula_variable VALUES(35, 10, 68);
INSERT INTO curricula_variable VALUES(25, 10, 84);
INSERT INTO curricula_variable VALUES(10, 60, 54);
INSERT INTO curricula_variable VALUES(50, 60, 67);
INSERT INTO curricula_variable VALUES(7, 60, 88);
INSERT INTO curricula_variable VALUES(15, 60, 78);
INSERT INTO curricula_variable VALUES(32, 60, 87);
INSERT INTO curricula_variable VALUES(56, 45, 69);
INSERT INTO curricula_variable VALUES(66, 45, 91);
INSERT INTO curricula_variable VALUES(43, 45, 56);
INSERT INTO curricula_variable VALUES(70, 20, 64);
INSERT INTO curricula_variable VALUES(54, 20, NULL);
INSERT INTO curricula_variable VALUES(53, 7, 84);
INSERT INTO curricula_variable VALUES(32, 17, 77);
INSERT INTO curricula_variable VALUES(3, 17, 65);
INSERT INTO curricula_variable VALUES(4, 17, 85);
INSERT INTO curricula_variable VALUES(5, 17, 96);
INSERT INTO curricula_variable VALUES(7, 17, 73);
INSERT INTO curricula_variable VALUES(15, 17, 65);
INSERT INTO curricula_variable VALUES(53, 17, 77);
INSERT INTO curricula_variable VALUES(50, 55, 75);
INSERT INTO curricula_variable VALUES(12, 55, 94);
INSERT INTO curricula_variable VALUES(25, 55, 85);
INSERT INTO curricula_variable VALUES(6, 55, 73);
INSERT INTO curricula_variable VALUES(7, 55, NULL);
INSERT INTO curricula_variable VALUES(45, 32, 80);
INSERT INTO curricula_variable VALUES(61, 32, 66);
INSERT INTO curricula_variable VALUES(51, 32, 88);
INSERT INTO curricula_variable VALUES(53, 14, NULL);
INSERT INTO curricula_variable VALUES(32, 14, 76);
INSERT INTO curricula_variable VALUES(8, 14, 84);
INSERT INTO curricula_variable VALUES(54, 14, 87);
INSERT INTO curricula_variable VALUES(33, 14, 67);
INSERT INTO curricula_variable VALUES(61, 14, 69);
INSERT INTO curricula_variable VALUES(51, 11, 75);
INSERT INTO curricula_variable VALUES(53, 11, 89);
INSERT INTO curricula_variable VALUES(66, 11, 99);
INSERT INTO curricula_variable VALUES(70, 11, 94);
INSERT INTO curricula_variable VALUES(52, 11, 86);
INSERT INTO curricula_variable VALUES(13, 11, 77);
INSERT INTO curricula_variable VALUES(15, 11, 84);
INSERT INTO curricula_variable VALUES(6, 11, 78);
INSERT INTO curricula_variable VALUES(5, 11, 67);
INSERT INTO curricula_variable VALUES(4, 37, 54);
INSERT INTO curricula_variable VALUES(10, 37, 62);
INSERT INTO curricula_variable VALUES(32, 37, 60);
INSERT INTO curricula_variable VALUES(42, 65, 55);
INSERT INTO curricula_variable VALUES(52, 65, 77);
INSERT INTO curricula_variable VALUES(25, 65, 99);
INSERT INTO curricula_variable VALUES(35, 65, 80);
INSERT INTO curricula_variable VALUES(5, 65, NULL);
INSERT INTO curricula_variable VALUES(11, 65, 77);
INSERT INTO curricula_variable VALUES(15, 63, 76);
INSERT INTO curricula_variable VALUES(14, 67, 75);
INSERT INTO curricula_variable VALUES(13, 61, 87);
INSERT INTO curricula_variable VALUES(16, 43, 83);
INSERT INTO curricula_variable VALUES(24, 48, 82);
INSERT INTO curricula_variable VALUES(35, 33, 89);
INSERT INTO curricula_variable VALUES(65, 9, 91);
INSERT INTO curricula_variable VALUES(70, 9, 92);
INSERT INTO curricula_variable VALUES(44, 9, 75);
INSERT INTO curricula_variable VALUES(34, 9, 78);
INSERT INTO curricula_variable VALUES(35, 9, 87);
INSERT INTO curricula_variable VALUES(25, 9, 65);
INSERT INTO curricula_variable VALUES(15, 56, 64);
INSERT INTO curricula_variable VALUES(50, 56, 84);
INSERT INTO curricula_variable VALUES(43, 56, NULL);
INSERT INTO curricula_variable VALUES(63, 56, 67);
INSERT INTO curricula_variable VALUES(33, 56, 82);
INSERT INTO curricula_variable VALUES(5, 56, 92);
INSERT INTO curricula_variable VALUES(6, 76, 60);
INSERT INTO curricula_variable VALUES(7, 76, 76);
INSERT INTO curricula_variable VALUES(8, 76, 70);
INSERT INTO curricula_variable VALUES(10, 76, 90);
INSERT INTO curricula_variable VALUES(13, 76, 80);
INSERT INTO curricula_variable VALUES(24, 76, 84);
INSERT INTO curricula_variable VALUES(22, 76, 67);
INSERT INTO curricula_variable VALUES(9, 76, 77);
INSERT INTO curricula_variable VALUES(69, 28, 84);
INSERT INTO curricula_variable VALUES(54, 28, 80);
INSERT INTO curricula_variable VALUES(53, 28, 63);
INSERT INTO curricula_variable VALUES(66, 28, 97);
INSERT INTO curricula_variable VALUES(45, 22, 66);
INSERT INTO curricula_variable VALUES(43, 22, 74);
INSERT INTO curricula_variable VALUES(55, 22, 65);
INSERT INTO curricula_variable VALUES(5, 22, 56);
INSERT INTO curricula_variable VALUES(15, 22, 78);
INSERT INTO curricula_variable VALUES(11, 22, 83);
INSERT INTO curricula_variable VALUES(34, 22, 85);
INSERT INTO curricula_variable VALUES(64, 21, 60);
INSERT INTO curricula_variable VALUES(33, 16, 78);
INSERT INTO curricula_variable VALUES(45, 73, 84);
INSERT INTO curricula_variable VALUES(66, 71, 55);
INSERT INTO curricula_variable VALUES(70, 71, 66);
INSERT INTO curricula_variable VALUES(44, 71, 85);
INSERT INTO curricula_variable VALUES(33, 38, 75);
INSERT INTO curricula_variable VALUES(25, 38, 76);
INSERT INTO curricula_variable VALUES(63, 59, 88);
INSERT INTO curricula_variable VALUES(43, 59, 83);
INSERT INTO curricula_variable VALUES(70, 59, 82);
INSERT INTO curricula_variable VALUES(66, 59, 81);
INSERT INTO curricula_variable VALUES(46, 59, 80);
INSERT INTO curricula_variable VALUES(41, 49, 89);
INSERT INTO curricula_variable VALUES(24, 49, 79);
INSERT INTO curricula_variable VALUES(15, 49, 78);
INSERT INTO curricula_variable VALUES(53, 49, NULL);
INSERT INTO curricula_variable VALUES(56, 49, 74);
INSERT INTO curricula_variable VALUES(45, 49, 63);
INSERT INTO curricula_variable VALUES(33, 49, 68);
INSERT INTO curricula_variable VALUES(23, 49, 73);
INSERT INTO curricula_variable VALUES(10, 49, 53);
INSERT INTO curricula_variable VALUES(11, 53, 59);
INSERT INTO curricula_variable VALUES(13, 53, 66);
INSERT INTO curricula_variable VALUES(25, 53, 44);
INSERT INTO curricula_variable VALUES(2, 75, 67);
INSERT INTO curricula_variable VALUES(34, 75, 80);
INSERT INTO curricula_variable VALUES(2, 78, 86);
INSERT INTO curricula_variable VALUES(1, 78, 88);
INSERT INTO curricula_variable VALUES(4, 78, 74);
INSERT INTO curricula_variable VALUES(6, 78, 77);
INSERT INTO curricula_variable VALUES(8, 78, 88);
INSERT INTO curricula_variable VALUES(7, 44, 89);
INSERT INTO curricula_variable VALUES(6, 46, 94);
INSERT INTO curricula_variable VALUES(43, 64, 92);
INSERT INTO curricula_variable VALUES(33, 74, 99);
INSERT INTO curricula_variable VALUES(12, 74, 93);
INSERT INTO curricula_variable VALUES(12, 15, 83);
INSERT INTO curricula_variable VALUES(4, 15, NULL);
INSERT INTO curricula_variable VALUES(33, 15, 64);
INSERT INTO curricula_variable VALUES(2, 51, 75);
INSERT INTO curricula_variable VALUES(50, 62, 85);
INSERT INTO curricula_variable VALUES(3, 40, 94);
